# Generated by Django 3.0.2 on 2021-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Patient First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Patient Last Name'),
        ),
    ]
