# Generated by Django 3.0.2 on 2021-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210313_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name="Patient's Mobile Number"),
        ),
    ]
