# Generated by Django 3.0.2 on 2021-03-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210313_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients Info'},
        ),
    ]
